// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'dart:async' as prefix7;
import 'dart_graphql_example.dart' as prefix1;
import 'package:dart_graphql/src/decorators/arg.dart' as prefix6;
import 'package:dart_graphql/src/decorators/field.dart' as prefix4;
import 'package:dart_graphql/src/decorators/objectType.dart' as prefix3;
import 'package:dart_graphql/src/decorators/query.dart' as prefix5;
import 'package:dart_graphql/src/decorators/reflector.dart' as prefix0;
import 'package:dart_graphql/src/decorators/resolver.dart' as prefix2;

// ignore_for_file: unnecessary_const

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_builder_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r"R1",
            r".R1",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[4, 5, 6, 7, 8],
            const <int>[9, 10, 11, 12, 13, 4, 5, 6, 7],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? prefix1.R1() : null},
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.reflector, const prefix2.Resolver()],
            null),
        r.NonGenericClassMirrorImpl(
            r"Page",
            r".Page",
            7,
            1,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 14, 21, 22],
            const <int>[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            const <int>[],
            -1,
            {},
            {},
            {
              r"": (b) =>
                  ([title = "defaultPage"]) => b ? prefix1.Page(title) : null
            },
            -1,
            1,
            const <int>[],
            const <Object>[
              prefix0.reflector,
              const prefix3.ObjectType(description: "Page with title")
            ],
            null),
        r.NonGenericClassMirrorImpl(
            r"ExPage",
            r".ExPage",
            7,
            2,
            const prefix0.Reflector(),
            const <int>[3, 25],
            const <int>[
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              23,
              24
            ],
            const <int>[],
            1,
            {},
            {},
            {r"": (b) => () => b ? prefix1.ExPage() : null},
            -1,
            2,
            const <int>[],
            const <Object>[prefix0.reflector, const prefix3.ObjectType()],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r"title",
            32773,
            1,
            const prefix0.Reflector(),
            -1,
            3,
            3,
            const <int>[],
            const <Object>[const prefix4.Field(description: "Title of Page")]),
        r.VariableMirrorImpl(r"rArray", 2129925, 1, const prefix0.Reflector(),
            -1, 4, 5, const <int>[6], const <Object>[const prefix4.Field()]),
        r.VariableMirrorImpl(
            r"futureArray",
            2129925,
            1,
            const prefix0.Reflector(),
            -1,
            7,
            8,
            const <int>[9],
            const <Object>[const prefix4.Field()]),
        r.VariableMirrorImpl(r"extra", 32773, 2, const prefix0.Reflector(), -1,
            3, 3, const <int>[], const <Object>[const prefix4.Field()]),
        r.MethodMirrorImpl(
            r"testPage",
            131074,
            0,
            1,
            1,
            1,
            const <int>[],
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[
              const prefix5.Query(description: "generate Test Page")
            ]),
        r.MethodMirrorImpl(
            r"multiplePages",
            4325378,
            0,
            -1,
            10,
            11,
            const <int>[1],
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[
              const prefix5.Query(description: "generate Multiple Pages")
            ]),
        r.MethodMirrorImpl(
            r"pageInputTitle",
            131074,
            0,
            1,
            1,
            1,
            const <int>[],
            const <int>[0],
            const prefix0.Reflector(),
            const <Object>[
              const prefix5.Query(description: "Page with input title")
            ]),
        r.MethodMirrorImpl(
            r"exPage",
            131074,
            0,
            2,
            2,
            2,
            const <int>[],
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[const prefix5.Query(description: "ExtraPage")]),
        r.MethodMirrorImpl(r"", 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r"==", 131074, null, -1, 12, 12, const <int>[],
            const <int>[1], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r"toString", 131074, null, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, null, null,
            const <int>[], const <int>[2], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r"hashCode", 131075, null, -1, 13, 13, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, 14, 14,
            const <int>[], const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(
            r"getCount",
            131074,
            1,
            -1,
            13,
            13,
            const <int>[],
            const <int>[3],
            const prefix0.Reflector(),
            const <Object>[const prefix4.Field(description: "Count")]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 3, 3, 15),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 3, 3, 16),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 4, 5, 17),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 4, 5, 18),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 7, 8, 19),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 7, 8, 20),
        r.MethodMirrorImpl(
            r"fStr",
            4325379,
            1,
            -1,
            15,
            16,
            const <int>[3],
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[const prefix4.Field()]),
        r.MethodMirrorImpl(r"", 0, 1, -1, 1, 1, const <int>[], const <int>[4],
            const prefix0.Reflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 3, 3, 23),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 3, 3, 3, 24),
        r.MethodMirrorImpl(r"", 64, 2, -1, 2, 2, const <int>[], const <int>[],
            const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r"title",
            32774,
            6,
            const prefix0.Reflector(),
            -1,
            3,
            3,
            const <int>[],
            const <Object>[const prefix6.Arg(desciption: "title of page")],
            null,
            null),
        r.ParameterMirrorImpl(r"other", 16390, 9, const prefix0.Reflector(),
            null, null, null, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r"invocation",
            32774,
            11,
            const prefix0.Reflector(),
            -1,
            17,
            17,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r"count",
            32774,
            14,
            const prefix0.Reflector(),
            -1,
            13,
            13,
            const <int>[],
            const <Object>[const prefix6.Arg()],
            null,
            null),
        r.ParameterMirrorImpl(r"title", 38918, 22, const prefix0.Reflector(),
            -1, 3, 3, const <int>[], const [], "defaultPage", null),
        r.ParameterMirrorImpl(r"_title", 32870, 16, const prefix0.Reflector(),
            -1, 3, 3, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r"_rArray",
            2130022,
            18,
            const prefix0.Reflector(),
            -1,
            4,
            5,
            const <int>[6],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r"_futureArray",
            2130022,
            20,
            const prefix0.Reflector(),
            -1,
            7,
            8,
            const <int>[9],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r"_extra", 32870, 24, const prefix0.Reflector(),
            -1, 3, 3, const <int>[], const [], null, null)
      ],
      <Type>[
        prefix1.R1,
        prefix1.Page,
        prefix1.ExPage,
        String,
        const m.TypeValue<List<List<int>>>().type,
        List,
        List,
        const m.TypeValue<prefix7.Future<List<List<String>>>>().type,
        prefix7.Future,
        List,
        const m.TypeValue<List<prefix1.Page>>().type,
        List,
        bool,
        int,
        Type,
        const m.TypeValue<prefix7.Future<String>>().type,
        prefix7.Future,
        Invocation
      ],
      3,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"testPage": (dynamic instance) => instance.testPage,
        r"multiplePages": (dynamic instance) => instance.multiplePages,
        r"pageInputTitle": (dynamic instance) => instance.pageInputTitle,
        r"exPage": (dynamic instance) => instance.exPage,
        r"getCount": (dynamic instance) => instance.getCount,
        r"title": (dynamic instance) => instance.title,
        r"rArray": (dynamic instance) => instance.rArray,
        r"futureArray": (dynamic instance) => instance.futureArray,
        r"fStr": (dynamic instance) => instance.fStr,
        r"extra": (dynamic instance) => instance.extra
      },
      {
        r"title=": (dynamic instance, value) => instance.title = value,
        r"rArray=": (dynamic instance, value) => instance.rArray = value,
        r"futureArray=": (dynamic instance, value) =>
            instance.futureArray = value,
        r"extra=": (dynamic instance, value) => instance.extra = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
