name: dart_graphql
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com
author: Deep Gaurav <deepgauravraj@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  reflectable: any
  graphql_parser: ^1.0.0
  graphql_schema: ^1.0.0
  graphql_server: ^1.0.0
  
dependency_overrides:
  graphql_server:
    path: ../sideproj/graphql/graphql_server


dev_dependencies:
  pedantic: ^1.8.0
  # test: ^1.6.0
  build_runner: ^1.0.0
  build_test: ^0.10.3
  logging: ^0.11.0
  angel_graphql: ^1.0.0
  angel_framework: ^2.0.0-alpha
